services:
  - type: web
    name: spu-skipq
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: MONGODB_URI
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
